-- ============================================
-- MIGRAÇÃO: Adicionar parcelas ao sistema
-- ============================================
-- Execute todo este SQL no SQL Editor do Supabase
-- (já deve estar aberto no seu navegador)

-- 1. Adicionar colunas à tabela loans
ALTER TABLE loans ADD COLUMN IF NOT EXISTS frequencia TEXT DEFAULT 'unique';
ALTER TABLE loans ADD COLUMN IF NOT EXISTS numero_parcelas INT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS valor_parcela DECIMAL(12,2);
ALTER TABLE loans ADD COLUMN IF NOT EXISTS dia_vencimento INT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS auto_notify BOOLEAN DEFAULT FALSE;

-- 2. Criar tabela de parcelas
CREATE TABLE IF NOT EXISTS pagamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id UUID REFERENCES loans(id) ON DELETE CASCADE,
  data_vencimento DATE NOT NULL,
  valor DECIMAL(12,2) NOT NULL,
  pago BOOLEAN DEFAULT FALSE,
  data_pagamento DATE,
  tipo TEXT DEFAULT 'juros',
  whatsapp_enviado BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

-- 3. Segurança (Row Level Security)
ALTER TABLE pagamentos ENABLE ROW LEVEL SECURITY;

-- Permitir SELECT apenas para o dono do empréstimo
CREATE POLICY "Usuarios podem ver seus proprios pagamentos" ON pagamentos
  FOR SELECT
  USING (loan_id IN (SELECT id FROM loans WHERE user_id = auth.uid()));

-- Permitir INSERT apenas em pagamentos vinculados aos seus empréstimos
CREATE POLICY "Usuarios podem inserir pagamentos" ON pagamentos
  FOR INSERT
  WITH CHECK (loan_id IN (SELECT id FROM loans WHERE user_id = auth.uid()));

-- Permitir UPDATE apenas em pagamentos vinculados aos seus empréstimos
CREATE POLICY "Usuarios podem atualizar pagamentos" ON pagamentos
  FOR UPDATE
  USING (loan_id IN (SELECT id FROM loans WHERE user_id = auth.uid()));

-- Permitir DELETE apenas em pagamentos vinculados aos seus empréstimos
CREATE POLICY "Usuarios podem deletar pagamentos" ON pagamentos
  FOR DELETE
  USING (loan_id IN (SELECT id FROM loans WHERE user_id = auth.uid()));
